apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jiva-w
  generation: 1
  labels:
    io.kompose.service: jiva-w
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: jiva-w
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
      labels:
        io.kompose.service: jiva-w
    spec:
      containers:
      - args:
        - sudo chown -R mgeweb:mgeweb /home/mgeweb/sankhyaw-dpm/ /home/mgeweb/SankhyaW/Anexos
          /home/mgeweb/repositorio /home/mgeweb/pacotes-sannfe/ && /home/mgeweb/DPM/scripts/./wildfly.sh
          ; java -jar /home/mgeweb/DPM/docker-package-manager.jar ; /home/mgeweb/DPM/scripts/./sannfe.sh;
          sudo chown -R mgeweb:mgeweb /home/mgeweb/SanNFe /home/mgeweb/wildfly_producao/standalone/log
          && /home/mgeweb/DPM/scripts/./visualvm.sh && sleep 10  && sed -i 's/<min-pool-size>100</<min-pool-size>10</g' && 
          /home/mgeweb/wildfly_producao/standalone/deployments/mge-ds.xml && sed -i
          's/<max-pool-size>100</<max-pool-size>50</g' /home/mgeweb/wildfly_producao/standalone/deployments/mge-ds.xml
          && sleep 30 ; /home/mgeweb/wildfly_producao/bin/./standalone.sh
          -Djape.lazy.init=true -Djape.lob.fields.as.lazy=true -Djape.ignore.ligacao.inconsistente=true
        command:
        - /bin/sh
        - -c
        env:
        - name: CLIENTE
          value: "{{ .Release.Namespace }}"
        - name: MEMORIA_JBOSS
          value: "{{ .Values.memoria.jivaw.jboss }}"
        {{ if not .Values.pacote.versionNew }}
        - name: PACOTE_JIVAW
          value: "{{ .Values.pacote.versao }}"
        {{- else }}
        - name: PACOTE_JIVAW
          value: "{{ .Values.pacote.versionNew }}"
        {{- end }}
        - name: PORTA_BD_JIVAW
          value: "{{ .Values.banco.porta }}"
        - name: TIPO_BD
          value: "{{ .Values.banco.tipo }}"
        - name: TIPO_SERVIDOR
          value: "WILDFLY"
        - name: SID_BD_JIVAW
          value: "{{ .Values.banco.sid }}"
        - name: IP_BD_JIVAW
          valueFrom:
            secretKeyRef:
              name: jiva-w
              key: banco-ip
        - name: SENHA_BD_JIVAW
          valueFrom:
            secretKeyRef:
              name: jiva-w
              key: banco-password
        - name: USUARIO_BD_JIVAW
          valueFrom:
            secretKeyRef:
              name: jiva-w
              key: banco-user 
        image: {{  .Values.imageRepository.jivaw.image }}:{{  .Values.imageRepository.jivaw.imageTag }}
        imagePullPolicy: IfNotPresent
        name: jiva-w
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 100
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 60
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 100
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 60
        resources:
          limits:
            memory: {{ .Values.memoria.jivaw.maximo }}Mi
          requests:
            memory: {{ .Values.memoria.jivaw.media }}Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
        volumeMounts:
        - mountPath: /home/mgeweb/repositorio
          name: volume-claim
          subPath: {{ .Release.Namespace }}/repositorio/
        - mountPath: /home/mgeweb/SanNFe
          name: volume-claim
          subPath: {{ .Release.Namespace }}/SanNFe/
        - mountPath: /home/mgeweb/SankhyaW/Anexos
          name: volume-claim
          subPath: {{ .Release.Namespace }}/Anexos/
        - mountPath: /home/mgeweb/pacotes-sannfe/
          name: volume-claim
          subPath: {{ .Release.Namespace }}/pacotes/sannfe/
        - mountPath: /home/mgeweb/sankhyaw-dpm/pkgs
          name: volume-claim
          subPath: {{ .Release.Namespace }}/jiva-w/
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: volume-claim
        persistentVolumeClaim:
          claimName: volume-claim
status: {}
